Update to ubuntu 22.04 with python3.10
TwistoPayments/eks-github-authenticator pull request #21
Opened 2024-02-12 10:57 UTC by mkutlak

## Decription
- Update docker image to newer Ubuntu relase 22.04
- Update python to version 3.10 (default in 22.04)
- Update versions of used workflows
- Step removed:
```
1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
```

closes #13, closes #14, closes #15, closes #16

2024-02-13 09:13 UTC, patakovamichaela reviewed
We should test it before we use it in prod. Just quick check for getting context.

2024-02-14 22:13 UTC, polanjir requested changes

2024-02-14 22:13 UTC, polanjir commented on Dockerfile
> +FROM ubuntu:22.04 AS builder
Maybe `python:3.10-slim-bookworm` would be better. `python3-dev` and `python3-pip` packages are already there.

2024-02-16 00:06 UTC, mkutlak commented
I've deployed this version on new cluster and it seems to work ok.
- it returns correct tokens and "error" messages

2024-02-17 09:22 UTC, polanjir approved these changes

2024-02-17 15:50 UTC, merged